
public class Tetst {
	public static void main(String [] arg){
	
		System.out.println("jdkf");
		//I WILL NOT LEAVE CODE UNDOCUMENTED!
		//I WILL NOT LEAVE CODE UNDOCUMENTED!
		//I WILL NOT LEAVE CODE UNDOCUMENTED!
		//I WILL NOT LEAVE CODE UNDOCUMENTED!
		//I WILL NOT LEAVE CODE UNDOCUMENTED!
		//I WILL NOT LEAVE CODE UNDOCUMENTED!
		//I WILL NOT LEAVE CODE UNDOCUMENTED!
		//I WILL NOT LEAVE CODE UNDOCUMENTED!!!!!
		//I WILL NOT LEAVE CODE UNDOCUMENTED!
		//I WILL NOT LEAVE CODE UNDOCUMENTED!
		//I WILL NOT LEAVE CODE UNDOCUMENTED!
		//I WILL NOT LEAVE CODE UNDOCUMENTED!
		//I WILL NOT LEAVE CODE UNDOCUMENTED!
		//I WILL NOT LEAVE CODE UNDOCUMENTED!
		//I WILL NOT LEAVE CODE UNDOCUMENTED!
		
	}
}
